### ISSUE TITLE
Create README in english

### ISSUE THREAD

**Issue by Akash190104** [salteadorneo/pokemodle#8]
If you assign me this. I would really like to create a README.md in ENGLISH for pokemodle.

**Comment by salteadorneo** [comment]
Thanks for supporting @Akash190104 🥇 

Would you like to translate the game too?

**Comment by Akash190104** [comment]
I would love to. But I need some instructions for that. Like which files would I need to add and where is the original file with Portuguese texts that I need to translate.

**Comment by Akash190104** [comment]
@salteadorneo Please review the changes. Thank you

**Comment by Akash190104** [comment]
@salteadorneo Can you please review this?
